name: Ryan Meyer Photography
favicon: null
layout_spectrum: 0.09706590231508017
typography_spectrum: 0.6143564861267805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.03301507979631424
  lightness: 0.26729235146194696
  saturation: 0.16662817005999386
  rhythmicContrast: 0.8310021935030818
purpose: []
